name: Bug Report
description: File a bug report
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - mlamota2020
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what do yo want to add?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: v2.1.0
    validations:
      required: true
  - type: textarea
    id: posible-error
    attributes:
      label: Have you seen an error?
      description: If you're requesting this feature beacuse of an error. Tell us that error.
      placeholder: I've seen this at...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mlamota2020/green-complaint/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
