name: Help issue
description: Decribe your doubts.
title: "[Help]: "
labels: ["help"]
assignees:
  - mlamota2020
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this help issue!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what's your problem?
      placeholder: I don't know how to create a new report and...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: v2.1.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mlamota2020/green-complaint/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
